apiVersion: networking.oci.upbound.io/v1alpha1
kind: Vcn
metadata:
  name: vdittaka-vcn-xp
spec:
  forProvider:
    compartmentId: "ocid1.compartment.oc1..aaaaaaaac4qhiyti5nwofgw7clrkxyo35umcjtztolrmc2tshwvvb7kng26a"
    displayName: vdittaka-vcn-xp
    cidrBlocks:
      - "10.1.0.0/16"
  providerConfigRef:
    name: default