apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oke-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/oracle/crossplane-provider-oci
    targetRevision: main
    path: argocd-examples/oke-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # ServerSideApply and Validate=false prevent webhook timeout issues
    # when creating XRDs/Compositions in Crossplane
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - Validate=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  # Ensure OKE providers are healthy before syncing
  ignoreDifferences:
    - group: apiextensions.crossplane.io
      kind: CompositeResourceDefinition
      jsonPointers:
        - /status
    - group: apiextensions.crossplane.io
      kind: Composition
      jsonPointers:
        - /status
